In [5]:
import torch
from torch.utils.data import Dataset, DataLoader

In [16]:
# Creating a dataset with 10 rows, 2 features, and 1 label (0 for 'off', 1 for 'on')
data = torch.tensor([
    [0.1, 0.5, 1],
    [0.4, 0.2, 0],
    [0.7, 0.8, 1],
    [0.3, 0.6, 0],
    [0.9, 0.1, 1],
    [0.2, 0.3, 0],
    [0.8, 0.7, 1],
    [0.5, 0.4, 0],
    [0.6, 0.9, 1],
    [0.3, 0.2, 0]
], dtype=torch.float32)

# Splitting features and labels
X = data[:, :2]  # First two columns are features
y = data[:, 2]  # Last column is the label

In [25]:
class CustomDataset(Dataset):
    def __init__(self,feature,label):
        self.features = feature
        self.labels = label
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [30]:
# Creating an instance of the dataset
dataset = CustomDataset(X, y)

In [31]:
len(dataset)

10

In [32]:
dataset[1]

(tensor([0.4000, 0.2000]), tensor(0.))

In [34]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [35]:
print(dataloader)

In [37]:
for i,j in dataloader:
    print(i)
    print(j)
    print("--"*20)

tensor([[0.8000, 0.7000],
        [0.2000, 0.3000]])
tensor([1., 0.])
----------------------------------------
tensor([[0.9000, 0.1000],
        [0.3000, 0.2000]])
tensor([1., 0.])
----------------------------------------
tensor([[0.1000, 0.5000],
        [0.5000, 0.4000]])
tensor([1., 0.])
----------------------------------------
tensor([[0.4000, 0.2000],
        [0.3000, 0.6000]])
tensor([0., 0.])
----------------------------------------
tensor([[0.6000, 0.9000],
        [0.7000, 0.8000]])
tensor([1., 1.])
----------------------------------------
