In [2]:
import numpy as np
import torch as t
import torch.nn as nn

In [16]:
class Model(nn.Module):
    def __init__(self,num_features):
        # super().__init_()
        super().__init__() 
        self.linear = nn.Linear(num_features,1) # it tatke input and output how many in and then out
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [17]:
features = t.rand(10,5)
features.shape

torch.Size([10, 5])

In [18]:
model = Model(features.shape[1])

In [19]:
# model.farward(features) #basically we have to do like this but pytorch recomend object calling for forward pass 
# like this 
model(features)

tensor([[0.3225],
        [0.2436],
        [0.2725],
        [0.2741],
        [0.2450],
        [0.3323],
        [0.2999],
        [0.3316],
        [0.2622],
        [0.3412]], grad_fn=<SigmoidBackward0>)

In [21]:
# finding weight
model.linear.weight

Parameter containing:
tensor([[-0.2411,  0.1114,  0.0641, -0.3889, -0.3594]], requires_grad=True)

In [22]:
# or bias
model.linear.bias

Parameter containing:
tensor([-0.4306], requires_grad=True)

In [23]:
# here we can visualize somehow
# !pip install torchinfo

In [24]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [25]:
# till now we have done on 5 input and one output or simply one neuron
# now 5 input which will produce 3 output then this 3 will go in one neuron so on..
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)  # First linear layer
        self.relu = nn.ReLU()  # ReLU activation function
        self.linear2 = nn.Linear(3, 1)  # Second linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation function
        
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)  # Apply ReLU after the first linear layer
        out = self.linear2(out)  # Apply the second linear layer
        out = self.sigmoid(out)  # Apply Sigmoid for the output
        return out

In [28]:
inp = t.rand(5,5)
inp.shape,inp

(torch.Size([5, 5]),
 tensor([[0.9816, 0.2909, 0.5955, 0.4587, 0.6481],
         [0.0617, 0.7980, 0.9621, 0.7724, 0.6916],
         [0.4287, 0.4448, 0.6080, 0.5360, 0.3347],
         [0.0247, 0.7581, 0.1780, 0.1100, 0.6113],
         [0.1187, 0.3069, 0.2400, 0.0636, 0.1362]]))

In [30]:
mdl = Model(inp.shape[1])

In [31]:
mdl(inp)

tensor([[0.4605],
        [0.4651],
        [0.4607],
        [0.4850],
        [0.4809]], grad_fn=<SigmoidBackward0>)

In [32]:
mdl.linear1.weight

Parameter containing:
tensor([[ 0.1712,  0.3978, -0.3817,  0.4413,  0.1160],
        [ 0.0978,  0.3184,  0.0217,  0.3657, -0.4453],
        [-0.0734,  0.4096, -0.1258,  0.1274, -0.0702]], requires_grad=True)

In [33]:
mdl.linear2.weight

Parameter containing:
tensor([[-0.2163, -0.3022,  0.3063]], requires_grad=True)

In [43]:
# in forward pass we pass each step manually it become hard if we have big network so we use container(sequential) for that
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3) , # First linear layer
            nn.ReLU() , # ReLU activation function
            nn.Linear(3, 1),  # Second linear layer
            nn.Sigmoid()  # Sigmoid activation function
            
        )
    def forward(self, features):
        return self.network(
            features
        )


In [44]:
inp = t.rand(5,5)
inp.shape,inp

(torch.Size([5, 5]),
 tensor([[0.2866, 0.1256, 0.5634, 0.8655, 0.6377],
         [0.7382, 0.0359, 0.9902, 0.1915, 0.5282],
         [0.6677, 0.9474, 0.5506, 0.7040, 0.1622],
         [0.9403, 0.0353, 0.5022, 0.0634, 0.4059],
         [0.8309, 0.4213, 0.6327, 0.4139, 0.2380]]))

In [45]:
mdl1 = Model(inp.shape[1])

In [46]:
mdl1(inp)

tensor([[0.3484],
        [0.3586],
        [0.3226],
        [0.3534],
        [0.3356]], grad_fn=<SigmoidBackward0>)