In [1]:
import numpy as np
import torch as t
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self,num_features):
        # super().__init_()
        super().__init__() 
        self.linear = nn.Linear(num_features,1) # it tatke input and output how many in and then out
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [3]:
features = t.rand(10,5)
features.shape

torch.Size([10, 5])

In [4]:
model = Model(features.shape[1])

In [5]:
# model.farward(features) #basically we have to do like this but pytorch recomend object calling for forward pass 
# like this 
model(features)

tensor([[0.4133],
        [0.3973],
        [0.4477],
        [0.3319],
        [0.3855],
        [0.4351],
        [0.4059],
        [0.4478],
        [0.3584],
        [0.3282]], grad_fn=<SigmoidBackward0>)

In [6]:
# finding weight
model.linear.weight

Parameter containing:
tensor([[ 0.2658, -0.0608, -0.1671, -0.3833,  0.2106]], requires_grad=True)

In [7]:
# or bias
model.linear.bias

Parameter containing:
tensor([-0.3324], requires_grad=True)

In [8]:
# here we can visualize somehow
# !pip install torchinfo

In [9]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
# till now we have done on 5 input and one output or simply one neuron
# now 5 input which will produce 3 output then this 3 will go in one neuron so on..
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)  # First linear layer
        self.relu = nn.ReLU()  # ReLU activation function
        self.linear2 = nn.Linear(3, 1)  # Second linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation function
        
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)  # Apply ReLU after the first linear layer
        out = self.linear2(out)  # Apply the second linear layer
        out = self.sigmoid(out)  # Apply Sigmoid for the output
        return out

In [11]:
inp = t.rand(5,5)
inp.shape,inp

(torch.Size([5, 5]),
 tensor([[0.8681, 0.7123, 0.1270, 0.7893, 0.8766],
         [0.3132, 0.8794, 0.9237, 0.5880, 0.8278],
         [0.0084, 0.2495, 0.9787, 0.9994, 0.2389],
         [0.4815, 0.9303, 0.3260, 0.0802, 0.8575],
         [0.1724, 0.1662, 0.1399, 0.8106, 0.9149]]))

In [12]:
mdl = Model(inp.shape[1])

In [13]:
mdl(inp)

tensor([[0.5041],
        [0.5279],
        [0.5259],
        [0.5187],
        [0.5088]], grad_fn=<SigmoidBackward0>)

In [19]:
mdl.linear1.weight

Parameter containing:
tensor([[-0.4241,  0.0467,  0.2841, -0.3425, -0.2360],
        [ 0.1807,  0.1659,  0.3161, -0.0856,  0.0344],
        [ 0.0638,  0.1606, -0.3449,  0.4213,  0.3258]], requires_grad=True)

In [18]:

for i in mdl.parameters():
    print(i)

Parameter containing:
tensor([[-0.4241,  0.0467,  0.2841, -0.3425, -0.2360],
        [ 0.1807,  0.1659,  0.3161, -0.0856,  0.0344],
        [ 0.0638,  0.1606, -0.3449,  0.4213,  0.3258]], requires_grad=True)
Parameter containing:
tensor([-0.4075, -0.3857, -0.0513], requires_grad=True)
Parameter containing:
tensor([[ 0.1468,  0.3825, -0.1612]], requires_grad=True)
Parameter containing:
tensor([0.1281], requires_grad=True)


In [15]:
mdl.linear2.weight

Parameter containing:
tensor([[ 0.1468,  0.3825, -0.1612]], requires_grad=True)

In [43]:
# in forward pass we pass each step manually it become hard if we have big network so we use container(sequential) for that
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3) , # First linear layer
            nn.ReLU() , # ReLU activation function
            nn.Linear(3, 1),  # Second linear layer
            nn.Sigmoid()  # Sigmoid activation function
            
        )
    def forward(self, features):
        return self.network(
            features
        )


In [44]:
inp = t.rand(5,5)
inp.shape,inp

(torch.Size([5, 5]),
 tensor([[0.2866, 0.1256, 0.5634, 0.8655, 0.6377],
         [0.7382, 0.0359, 0.9902, 0.1915, 0.5282],
         [0.6677, 0.9474, 0.5506, 0.7040, 0.1622],
         [0.9403, 0.0353, 0.5022, 0.0634, 0.4059],
         [0.8309, 0.4213, 0.6327, 0.4139, 0.2380]]))

In [45]:
mdl1 = Model(inp.shape[1])

In [46]:
mdl1(inp)

tensor([[0.3484],
        [0.3586],
        [0.3226],
        [0.3534],
        [0.3356]], grad_fn=<SigmoidBackward0>)