In [1]:
import torch as t

In [82]:
print(t.__version__)

2.5.1+cu124


In [85]:
if t.cuda.is_available():
    print("GPU is available")
    print("GPU is ",t.cuda.get_device_name())
else:
    print("GPU is not available")

GPU is available
GPU is  NVIDIA GeForce GTX 1650


In [ ]:
# creating tensor in pytorch
t.empty(2,3) #it allocate memory for us 

In [ ]:
# using zeros
t.zeros(3,3)

In [ ]:
# using ones
t.ones(2,2)

In [ ]:
# using rand
t.rand(3,3)

In [ ]:
# manual seed 
t.manual_seed(10)
t.rand(2,2)

In [ ]:
# using tensor or making custom tensor
t.tensor([[2],[3]])

In [ ]:
# arrange
t.arange(0,5,1)

In [ ]:
# using linspace it is linear space
t.linspace(1,6,2)

In [ ]:
# using eye or identity matrix or tensor
t.eye(5)

In [ ]:
# using full it fill with costum values
t.full((2,2),3)

In [3]:
# tensor shapes


In [4]:
x = t.tensor([[1,2,3],[4,5,6]])

In [5]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
x.shape

torch.Size([2, 3])

In [7]:
 # if you wnat to make tensor with same previous tensor shape
t.empty_like(x)

tensor([[          351879261,                   0,        485331304447],
        [7882770745416578145, 7598263560199304304, 8317129565128648036]])

In [8]:
# or we also have 
t.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
# or 
t.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [10]:
# tensor datat type
x.dtype

torch.int64

In [11]:
# we can specify data type 
y = t.tensor([[1,2,3],[2,3,4]],dtype=t.float32)

In [12]:
y

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [13]:
# also we can change it 
y.to(t.int32)

tensor([[1, 2, 3],
        [2, 3, 4]], dtype=torch.int32)

In [14]:
# mathematical operation 
# 1 scalar operation
a = t.rand(2,3)
2+a

tensor([[2.2972, 2.0268, 2.6398],
        [2.1219, 2.5815, 2.7252]])

In [15]:
2-a

tensor([[1.7028, 1.9732, 1.3602],
        [1.8781, 1.4185, 1.2748]])

In [16]:
2*a

tensor([[0.5945, 0.0537, 1.2796],
        [0.2437, 1.1630, 1.4503]])

In [20]:
a/2 #this is simple division
a//2 #this is integer division

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
a%2

tensor([[0.2972, 0.0268, 0.6398],
        [0.1219, 0.5815, 0.7252]])

In [22]:
a**2

tensor([[0.0884, 0.0007, 0.4094],
        [0.0149, 0.3381, 0.5258]])

In [31]:
b = t.rand(2,3)

In [32]:
# a,b
a.shape

torch.Size([2, 3])

In [35]:
# element wise operation
a + b # print it if you want
a - b # print it if you want
a * b # print it if you want
a / b # printing

tensor([[0.9343, 0.0297, 1.8973],
        [1.5910, 0.6171, 2.5470]])

In [37]:
# aboslute value
t.abs(a) #each element will come like this

tensor([[0.2972, 0.0268, 0.6398],
        [0.1219, 0.5815, 0.7252]])

In [38]:
# similar ceil and floor
# clamping operation
# t.clamp() # it clamping or ranging value

In [40]:
# reduction operation
x = t.rand(3,3)
x

tensor([[0.5683, 0.5701, 0.0019],
        [0.8946, 0.3499, 0.3361],
        [0.5051, 0.9132, 0.8269]])

In [41]:
t.sum(x)

tensor(4.9660)

In [42]:
# or if want to column wise axis 0 is for column and 1 is for rowvice
t.sum(x,axis=0)

tensor([1.9680, 1.8331, 1.1649])

In [46]:
t.mean(x)

tensor(0.5518)

In [47]:
t.mean(x,axis=1)

tensor([0.3801, 0.5269, 0.7484])

In [49]:
# there are so many mathematical operation that we can perform 
# like mat multiplication(dot product) transpose and determinant etc so on...
# google it or see documentation of it


In [50]:
# comparision operation
a > b

tensor([[False, False,  True],
        [ True, False,  True]])

In [51]:
a < b

tensor([[ True,  True, False],
        [False,  True, False]])

In [52]:
a == b

tensor([[False, False, False],
        [False, False, False]])

In [53]:
a != b

tensor([[True, True, True],
        [True, True, True]])

In [54]:
a >= b

tensor([[False, False,  True],
        [ True, False,  True]])

In [55]:
a <= b

tensor([[ True,  True, False],
        [False,  True, False]])

In [56]:
t.log(a)

tensor([[-1.2132, -3.6182, -0.4466],
        [-2.1049, -0.5422, -0.3214]])

In [57]:
t.exp(a)

tensor([[1.3461, 1.0272, 1.8961],
        [1.1296, 1.7887, 2.0650]])

In [58]:
t.sqrt(a)

tensor([[0.5452, 0.1638, 0.7999],
        [0.3491, 0.7626, 0.8516]])

In [59]:
t.sigmoid(a)

tensor([[0.5738, 0.5067, 0.6547],
        [0.5304, 0.6414, 0.6737]])

In [61]:
t.softmax(a,axis=1) #dimension must be give

tensor([[0.3153, 0.2406, 0.4441],
        [0.2267, 0.3589, 0.4144]])

In [69]:
# inplace operation
# _ this underscore change operation in inplace
m = t.rand(2,2)
n = t.rand(2,2)

In [70]:
m.add_(n)

tensor([[1.1087, 1.5055],
        [1.4703, 0.6141]])

In [71]:
m

tensor([[1.1087, 1.5055],
        [1.4703, 0.6141]])

In [72]:
t.relu_(m)

tensor([[1.1087, 1.5055],
        [1.4703, 0.6141]])

In [73]:
m

tensor([[1.1087, 1.5055],
        [1.4703, 0.6141]])

In [75]:
# copying a tensor
c = a.clone() # it deeply copy a tensor

In [76]:
# performing tensor operation on gpu

In [77]:
device = t.device('cuda')

In [78]:
device

device(type='cuda')

In [80]:
# creating a new tensor on GPU
t.rand((2,3),device=device)

tensor([[0.1761, 0.6925, 0.7344],
        [0.4357, 0.7037, 0.0104]], device='cuda:0')

In [88]:
# exiting tensor shift on gpu
a = m.to(m)

In [97]:
import torch
import time

# Set device to CPU for the first part
device_cpu = torch.device('cpu')

# Create two random matrices on CPU (size 1000x1000 for example)
matrix_a_cpu = torch.randn(10000, 10000, device=device_cpu)
matrix_b_cpu = torch.randn(10000, 10000, device=device_cpu)

# Time the multiplication on CPU
start_time_cpu = time.time()
result_cpu = torch.mm(matrix_a_cpu, matrix_b_cpu)  # Matrix multiplication
end_time_cpu = time.time()

cpu_time = end_time_cpu - start_time_cpu
print(f"Matrix multiplication on CPU took: {cpu_time:.6f} seconds")

# Set device to GPU if available
device_gpu = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device_gpu)
# Move the matrices to GPU
matrix_a_gpu = matrix_a_cpu.to(device_gpu)
matrix_b_gpu = matrix_b_cpu.to(device_gpu)

# Time the multiplication on GPU
start_time_gpu = time.time()
result_gpu = torch.mm(matrix_a_gpu, matrix_b_gpu)  # Matrix multiplication on GPU
end_time_gpu = time.time()

gpu_time = end_time_gpu - start_time_gpu
print(f"Matrix multiplication on GPU took: {gpu_time:.6f} seconds")


Matrix multiplication on CPU took: 3.538332 seconds
cuda
Matrix multiplication on GPU took: 0.000143 seconds


In [100]:
# reshping tensor
a = t.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
# unsquze it adding additional dimension in 
# where you want to put you can
x = t.rand(2,2)
x.shape,x

(torch.Size([2, 2]),
 tensor([[0.5742, 0.3826],
         [0.4001, 0.0481]]))

In [120]:
x.unsqueeze(2)

tensor([[[0.5742],
         [0.3826]],

        [[0.4001],
         [0.0481]]])

In [121]:
x.unsqueeze(2).shape

torch.Size([2, 2, 1])

In [123]:
# squeez is its opposite one
x.squeeze(0)

tensor([[0.5742, 0.3826],
        [0.4001, 0.0481]])

In [ ]:
# numpy vs pytorch and interoperability
# it is so easy to work each other 
