In [1]:
%matplotlib inline
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, linewidth=75)

In [2]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0,
                    8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])
t_un = 0.1 * t_u

### Note (Cell 3): Model function

Defines a simple linear model `model(t_u, w, b)` that returns `w * t_u + b`. This keeps the math explicit and avoids nn.Module complexity for teaching purposes.

In [3]:
def model(t_u, w, b):
    return w * t_u + b

### Note (Cell 4): Loss function

Defines `loss_fn(t_p, t_c)` to compute mean squared error (MSE) using `((t_p - t_c)**2).mean()`. This is the optimization objective.

In [4]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

### Note (Cell 5): Optimizers exploration

Imports `torch.optim` as `optim` and lists available optimizer classes with `dir(optim)`. This is for educational discovery of available optimizers (SGD, Adam, etc.).

In [5]:
import torch.optim as optim

dir(optim)

['ASGD',
 'Adadelta',
 'Adafactor',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'NAdam',
 'Optimizer',
 'RAdam',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_adafactor',
 '_functional',
 'lr_scheduler',
 'swa_utils']

### Note (Cell 6): Initialize parameters and SGD (tiny LR)

Creates `params = torch.tensor([w, b], requires_grad=True)` and an `optim.SGD` optimizer that will update `params`. Learning rate is very small here to illustrate slow updates.

In [6]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)

### Note (Cell 7): Forward/backward/step (no zero_grad)

Runs one forward pass (`t_p`), computes `loss` and calls `loss.backward()` followed by `optimizer.step()`. No `optimizer.zero_grad()` is called here — this shows what happens when gradients are not cleared (they would accumulate on repeated calls).

In [7]:
t_p = model(t_u, *params)
loss = loss_fn(t_p, t_c)
loss.backward()

optimizer.step()

params

tensor([ 9.5483e-01, -8.2600e-04], requires_grad=True)

### Note (Cell 8): Proper single-step update with zero_grad

Reinitializes parameters and uses a larger LR. Calls `optimizer.zero_grad()` before `loss.backward()` to prevent gradient accumulation, then `optimizer.step()` to update parameters — the correct single-update pattern.

In [8]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

t_p = model(t_un, *params)
loss = loss_fn(t_p, t_c)

optimizer.zero_grad() # <1>
loss.backward()
optimizer.step()

params

tensor([1.7761, 0.1064], requires_grad=True)

### Note (Cell 9): `training_loop` function

Defines `training_loop(n_epochs, optimizer, params, t_u, t_c)` that runs repeated forward/backward/step updates. Prints the loss every 500 epochs. Returns the final `params` for inspection.

In [9]:
def training_loop(n_epochs, optimizer, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        t_p = model(t_u, *params) 
        loss = loss_fn(t_p, t_c)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
            
    return params

### Note (Cell 10): Run training_loop with SGD

Re-initializes `params` and `optimizer` and runs `training_loop` for 5000 epochs using SGD. This cell demonstrates training convergence behaviour with SGD and the specified LR.

In [10]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params, # <1> 
    t_u = t_un,
    t_c = t_c)

Epoch 500, Loss 7.860118
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957697
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927680
Epoch 4500, Loss 2.927651
Epoch 5000, Loss 2.927648


tensor([  5.3671, -17.3012], requires_grad=True)

### Note (Cell 11): Use Adam optimizer

Shows switching to `optim.Adam` with a larger learning rate. Adam adapts step sizes per-parameter and often converges faster; this cell runs `training_loop` for fewer epochs to illustrate that.

In [11]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.Adam([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 2000, 
    optimizer = optimizer,
    params = params,
    t_u = t_u, # <2> 
    t_c = t_c)

Epoch 500, Loss 7.612903
Epoch 1000, Loss 3.086700
Epoch 1500, Loss 2.928578
Epoch 2000, Loss 2.927646


tensor([  0.5367, -17.3021], requires_grad=True)

### Note (Cell 12): Training with Adam

This cell reinitializes parameters and runs `training_loop` with Adam for 2000 epochs. It compares optimizer behaviour and shows different convergence characteristics than SGD.

In [12]:
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices  # <1>

(tensor([9, 6, 5, 8, 4, 7, 0, 1, 3]), tensor([ 2, 10]))

### Note (Cell 13): Create train/validation split

Computes `n_val` as 20% of samples, shuffles indices with `torch.randperm`, and splits indices into training and validation. This is a simple deterministic split used for demonstration.

In [13]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]

val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]

train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u

### Note (Cell 14): Build train/validation tensors

Uses the split indices to create `train_t_u`, `train_t_c`, `val_t_u`, `val_t_c` and scaled versions `train_t_un`, `val_t_un`. These are the tensors used in training/validation calls.

In [14]:
def training_loop(n_epochs, optimizer, params, train_t_u, val_t_u,
                  train_t_c, val_t_c):
    for epoch in range(1, n_epochs + 1):
        train_t_p = model(train_t_u, *params) # <1>
        train_loss = loss_fn(train_t_p, train_t_c)
                             
        val_t_p = model(val_t_u, *params) # <1>
        val_loss = loss_fn(val_t_p, val_t_c)
        
        optimizer.zero_grad()
        train_loss.backward() # <2>
        optimizer.step()

        if epoch <= 3 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")
            
    return params

### Note (Cell 16): Call training_loop on training split

Re-initializes `params` and `optimizer`, then calls the train/validation `training_loop` for 3000 epochs using the scaled training inputs (`train_t_un`) and validation inputs. This shows training with a held-out validation set.

### Note (Cell 15): Train/validation `training_loop` variant

This `training_loop` accepts train and validation tensors. It computes both training and validation loss each epoch, zeroes gradients, backprops the training loss only, and steps the optimizer. Periodically prints both losses for monitoring.

In [15]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 3000, 
    optimizer = optimizer,
    params = params,
    train_t_u = train_t_un, # <1> 
    val_t_u = val_t_un, # <1> 
    train_t_c = train_t_c,
    val_t_c = val_t_c)

Epoch 1, Training loss 66.5811, Validation loss 142.3890
Epoch 2, Training loss 38.8626, Validation loss 64.0434
Epoch 3, Training loss 33.3475, Validation loss 39.4590
Epoch 500, Training loss 7.1454, Validation loss 9.1252
Epoch 1000, Training loss 3.5940, Validation loss 5.3110
Epoch 1500, Training loss 3.0942, Validation loss 4.1611
Epoch 2000, Training loss 3.0238, Validation loss 3.7693
Epoch 2500, Training loss 3.0139, Validation loss 3.6279
Epoch 3000, Training loss 3.0125, Validation loss 3.5756


tensor([  5.1964, -16.7512], requires_grad=True)

### Note (Cell 17): `no_grad` validation pattern

This variant of `training_loop` computes validation loss inside `with torch.no_grad():` so autograd is disabled during validation. This reduces memory usage and ensures validation does not affect gradients.

In [16]:
def training_loop(n_epochs, optimizer, params, train_t_u, val_t_u,
                  train_t_c, val_t_c):
    for epoch in range(1, n_epochs + 1):
        train_t_p = model(train_t_u, *params)
        train_loss = loss_fn(train_t_p, train_t_c)

        with torch.no_grad(): # <1>
            val_t_p = model(val_t_u, *params)
            val_loss = loss_fn(val_t_p, val_t_c)
            assert val_loss.requires_grad == False # <2>
            
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

### Note (Cell 18): `calc_forward` helper with `set_grad_enabled`

Defines `calc_forward(t_u, t_c, is_train)` which uses `torch.set_grad_enabled(is_train)` to toggle autograd during a forward pass and returns the computed loss. Useful for unified train/val forward logic.

In [17]:
def calc_forward(t_u, t_c, is_train):
    with torch.set_grad_enabled(is_train):
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)
    return loss